// minimal app using previous logic but no profiles to keep file shorter
const STORAGE='tus_big_v1';
let data={questions:[],info:[]};
let stats=JSON.parse(localStorage.getItem(STORAGE)||'{"total":0,"correct":0,"streak":0,"cats":{},"seenQ":[],"seenI":[],"wrong":[]}');
function save(){localStorage.setItem(STORAGE,JSON.stringify(stats))}
function byId(x){return document.getElementById(x)};function hide(el,b){el.classList.toggle('hidden',!!b)}
async function loadData(){const q=await fetch('data/questions.json').then(r=>r.json());data=q;fillCats();}
function fillCats(){const sel=byId('category');sel.innerHTML='';const cats=[...new Set(data.questions.map(x=>x.category))].sort();cats.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o)})}
function cats(){const sel=byId('category');const v=[...sel.selectedOptions].map(o=>o.value);return v.length?v:[...new Set(data.questions.map(x=>x.category))]}
function poolQ(){const c=cats();let p=data.questions.filter(q=>c.includes(q.category));if(byId('onlyWrong').checked){p=p.filter(q=>stats.wrong.includes(q.id))}else{p=p.filter(q=>!stats.seenQ.includes(q.id))}return p}
function pickQ(){const p=poolQ();if(!p.length){alert('Havuz bitti, sıfırlanıyor.');stats.seenQ=[];save();return pickQ()}const w=p.map(q=>stats.wrong.includes(q.id)?3:1);let r=Math.random()*w.reduce((a,b)=>a+b,0);for(let i=0;i<p.length;i++){if((r-=w[i])<0)return p[i]}return p[0]}
function renderQ(q){window.cur=q;byId('q-id').textContent=q.id;byId('q-cat').textContent=q.category;byId('q-text').textContent=q.prompt;const ul=byId('choices');ul.innerHTML='';['A','B','C','D'].forEach(k=>{const li=document.createElement('li');li.className='choice';li.dataset.choice=k;li.textContent=`${k}) ${q['choice_'+k.toLowerCase()]}`;li.onclick=choose;ul.appendChild(li)});byId('explanation').textContent=q.explanation||'';hide(byId('explanation'),true);hide(byId('quiz-card'),false);hide(byId('info-card'),true)}
function choose(e){const ch=e.currentTarget.dataset.choice;const q=window.cur;document.querySelectorAll('.choice').forEach(li=>{const ok=li.dataset.choice===q.correct;li.classList.toggle('correct',ok);if(li.dataset.choice===ch&&!ok)li.classList.add('wrong');li.onclick=null});if(!stats.seenQ.includes(q.id))stats.seenQ.push(q.id);stats.total++;if(ch===q.correct){stats.correct++;stats.streak++;stats.wrong=stats.wrong.filter(id=>id!==q.id)}else{stats.streak=0;if(!stats.wrong.includes(q.id))stats.wrong.push(q.id)};stats.cats[q.category]=stats.cats[q.category]||{t:0,c:0};stats.cats[q.category].t++;stats.cats[q.category].c+=(ch===q.correct?1:0);save();hide(byId('explanation'),false);refresh()}
function pickInfo(){const c=cats();let p=data.info.filter(x=>!x.category||c.includes(x.category)).filter(x=>!stats.seenI.includes(x.id));if(!p.length){stats.seenI=[];save();p=data.info.filter(x=>!x.category||c.includes(x.category))}return p[Math.floor(Math.random()*p.length)]}
function renderInfo(it){if(!it)return;byId('info-cat').textContent=it.category||'';byId('info-text').textContent=it.title;byId('info-extra').textContent=it.text||'';if(!stats.seenI.includes(it.id))stats.seenI.push(it.id);save();hide(byId('quiz-card'),true);hide(byId('info-card'),false)}
function refresh(){byId('st-total').textContent=stats.total;byId('st-correct').textContent=stats.correct;byId('st-acc').textContent=stats.total?Math.round(100*stats.correct/stats.total)+'%':'0%';byId('st-streak').textContent=stats.streak;const ul=byId('st-cats');ul.innerHTML='';Object.entries(stats.cats).forEach(([k,v])=>{const li=document.createElement('li');const a=v.t?Math.round(100*v.c/v.t):0;li.textContent=`${k}: ${v.c}/${v.t} (${a}%)`;ul.appendChild(li)})}
function parseCSV(t){const L=t.replace(/\r/g,'').split('\n').filter(x=>x.trim().length);const H=L.shift().split(',').map(s=>s.trim());return L.map(line=>{const c=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch=='"'){q=!q;continue}if(ch==','&&!q){c.push(cur);cur=''}else{cur+=ch}}c.push(cur);const o={};H.forEach((h,i)=>o[h]=c[i]||'');return o})}
function rowsToQ(rows){return rows.map(r=>({id:r.id||`CSV-${Math.random().toString(36).slice(2,8)}`,category:r.category||'Genel',prompt:r.prompt||'',choice_a:r.choice_a||'',choice_b:r.choice_b||'',choice_c:r.choice_c||'',choice_d:r.choice_d||'',correct:(r.correct||'A').toUpperCase(),explanation:r.explanation||''}))}
byId('file-input').addEventListener('change',e=>{[...e.target.files].forEach(f=>{const R=new FileReader();R.onload=()=>{if(f.name.endsWith('.json')){const o=JSON.parse(R.result);if(o.questions)data.questions=data.questions.concat(o.questions);if(o.info)data.info=data.info.concat(o.info);fillCats();alert(f.name+' eklendi')}else{const rows=parseCSV(R.result);const qs=rowsToQ(rows);data.questions=data.questions.concat(qs);fillCats();alert(f.name+': '+qs.length+' soru')}};R.readAsText(f,'utf-8')})})
byId('btn-new').onclick=()=>{const q=pickQ();if(q)renderQ(q)};byId('btn-reveal').onclick=()=>byId('explanation').classList.remove('hidden');byId('btn-next').onclick=()=>{const q=pickQ();if(q)renderQ(q)};byId('mode-quiz').onclick=()=>{const q=pickQ();if(q)renderQ(q)};byId('mode-info').onclick=()=>renderInfo(pickInfo());byId('reset-stats').onclick=()=>{if(confirm('Sıfırlansın mı?')){stats={total:0,correct:0,streak:0,cats:{},seenQ:[],seenI:[],wrong:[]};save();refresh()}};
window.addEventListener('DOMContentLoaded',async()=>{await loadData();refresh();const q=pickQ();if(q)renderQ(q)})